name: Dependency Vulnerability Check

on: 
  push:
    paths:
      - '**/go.mod'
      - '**/go.sum'
jobs:
  path-filter:
    name: Path Filter
    runs-on: ubuntu-latest
    outputs:
      any-modified-files: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Verify Changed files
        uses: tj-actions/changed-files@4daffbaee17b34b8ae544990906277485819cc16 # v16
        id: changed-files
        with:
          # If any of these file paths are modified, we want to run successive
          # jobs in this workflow.
          files: |
            **/go.mod
            **/go.sum

  Go:
    needs: path-filter
    if: any-modified-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Write Go Modules list
        run: go list -json -m all > go.list

      - name: Check vulnerabilities
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
          nancyVersion: "v1.0.22"

