name: golangci-lint

on:
  push:
    branches:
      - auto
      - try
      - rollup
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No job required" '
