##
# NOTE: any changes to the event triggers or the paths here should be reflected in:
#       golangci-lint-paths-ignore.yml
##

name: golangci-lint

on:
  push:
    branches:
      - auto
      - try
      - rollup
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No job required" '
