name: Solidity

on:
  push:
    branches:
      - auto
      - try
      - rollup
  pull_request:

jobs:
  path-filter:
    name: Path Filter
    runs-on: ubuntu-latest
    outputs:
      any-modified-files: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Verify Changed files
        uses: tj-actions/changed-files@4daffbaee17b34b8ae544990906277485819cc16 # v16
        id: changed-files
        with:
          # If any of these file paths are modified, we want to run successive
          # jobs in this workflow.
          files: |
            contracts/**
            yarn.lock
            tools/ci/**
  
  solidity-coverage:
    name: Solidity Coverage
    needs: path-filter
    if: any-modified-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: |
            ~/.npm
            ~/.cache
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn install --frozen-lockfile
      - name: Run coverage
        env:
          NODE_OPTIONS: "--max-old-space-size=5120"
        run: ./tools/ci/contracts/solidity_coverage

  solidity:
    name: Solidity
    needs: solidity-path-filter
    if: any-modified-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: |
            ~/.npm
            ~/.cache
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn install --frozen-lockfile
      - name: Compile all contracts
        run: ./contracts/scripts/native_solc_compile_all
      - name: Verify local solc binaries
        run: ./tools/ci/check_solc_hashes
      - name: Run tests
        run: ./tools/ci/solidity_test_hardhat
      - name: Run prepublish NPM test
        run: ./tools/ci/prepublish_npm_test
